# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
general:
  branches:
    only:
      - master
jobs:
  build:
    docker:
      - image: ns8inc/nodeaws:latest
    steps:
      - checkout

      - run:
          name: Increment version and commit changes
          command: |
                   git config user.email "circleci@ns8.com"
                   git config user.name "CircleCI"
                   yarn config set version-git-message "v%s [ci skip]"
                   yarn version --patch 
                   git push origin master --tags

      - run: 
          name: setup npm credentials
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc

      - run: yarn install
      - run: yarn lint
      - run: yarn test
      - run: yarn build
      - run:
          name: Publish to npm
          command: npm publish
