version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.13

jobs:

  build-magento-module:
    docker:
      - image: ns8inc/nodeaws:latest
    steps:
      - add_ssh_keys:
          fingerprints:
            - "91:b0:e2:c9:d6:89:9c:35:cb:88:ba:53:a9:fa:13:fd"

      - attach_workspace:
          at: /tmp/workspace

      - run:
          name: Clone ns8-magento-module repo
          command: git clone git@github.com:ns8inc/ns8-magento-module.git

      - run:
          name: Copy files to ns8-magento-module project
          command: |
            cp -r module/. ns8-magento-module/
      - run:
          name: Stage changes to ns8-magento-module
          working_directory: ns8-magento-module
          command: |
            git config user.email "circleci@ns8.com"
            git config user.name "CircleCI"
            git add -A
      - run:
          name: Commit changes to ns8-magento-module
          working_directory: ns8-magento-module
          command: |
            git diff-index --quiet HEAD || git commit -m "$(git --git-dir ../.git log -1 --pretty=%s)"
      - run:
          name: push changes to ns8-magento-module
          working_directory: ns8-magento-module
          command: |
            git push -v origin master
workflows:
  version: 2
  build-deploy:
    jobs:
      - build-magento-module