jobs:
  deploy:
    docker:
      - image: php:7.3-cli
    steps:
      - run:
          command: |
            apt-get update
            apt-get install -y git
          name: Install Git
      - checkout
      - run:
          command: |
            git config user.email noreply@ns8.com
            git config user.name 'CircleCI'
          name:
            Setup Git
      - run:
          command: |
            version=$(git tag -l | sort -V | tail -n 1 | awk -F . '{$NF+=1; print $0}' OFS=".") # Find highest version tag
            version="${version:-0.0.0}" # If the repo has no tags, default the initial version to 0.0.0
            git tag $version
            if ! git push origin $version; then
              echo "Push failed. Please delete and re-add this CircleCI deploy key to your repo with write access:"
              ssh-keygen -y -f ~/.ssh/id_rsa
              exit 1
            fi
          name: Bump Version
  test:
    docker:
      - image: php:7.3-cli
    steps:
      - run:
          command: |
            apt-get update
            apt-get install -y git
          name: Install Git
      - checkout
      - run:
          command: apt-get install -y unzip wget
          name: Install Tools
      - run:
          command: apt-get install -y libicu-dev libpng-dev libxslt1-dev libzip-dev
          name: Install Libraries
      - run:
          command: docker-php-ext-install bcmath gd intl pdo_mysql soap sockets xsl zip
          name: Install PHP Extensions
      - run:
          command: |
            pecl install xdebug
            docker-php-ext-enable xdebug
          name: Install XDebug
      - run:
          command: |
            cd /tmp
            expected_signature="$(wget -q -O - https://composer.github.io/installer.sig)"
            php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
            actual_signature="$(php -r "echo hash_file('sha384', 'composer-setup.php');")"
            if [ "$expected_signature" != "$actual_signature" ]; then
              >&2 echo 'ERROR: Invalid installer signature'
              exit 1
            fi
            php composer-setup.php --filename=composer --install-dir=/usr/local/bin --quiet
          name: Install Composer
      - run:
          command: composer install --no-ansi --no-autoloader
          name: Install Module
      - run:
          command: |
            vendor/bin/phpcs --config-set installed_paths vendor/magento/magento-coding-standard/Magento2
            composer lint
          name: Lint
      - run:
          command: |
            curl -o /tmp/magento.zip https://$MAGENTO_USER:$MAGENTO_PASS@www.magentocommerce.com/products/downloads/file/Magento-CE-${MAGENTO_VERSION}_sample_data.zip
            unzip -q /tmp/magento.zip -d /tmp/magento
            composer install -d /tmp/magento --no-ansi
            mkdir -p /tmp/magento/app/code/NS8
            ln -s $(pwd) /tmp/magento/app/code/NS8/Protect
          name: Install Magento
      - run:
          command: |
            chmod 755 /tmp/magento/vendor/phpunit/phpunit/phpunit
            /tmp/magento/vendor/phpunit/phpunit/phpunit -c /tmp/magento/dev/tests/unit/phpunit.xml.dist /tmp/magento/app/code/NS8/Protect/Test
          name: Run Tests

version: 2.1

workflows:
  test_and_deploy:
    jobs:
      - test
      - deploy:
          filters:
            branches:
              only: master
          requires:
            - test
