<script type="text/javascript" src="<?= $block->url->getProtectClientSdkUrl() ?>"></script>
<script type="text/javascript">
  require(['Protect'], function (Protect) {
    // this isn't compiled, so we have to use old JS to work in old browsers
    function navigateToMagentoOrderDetails(orderData) {
      var orderDetailsUrlBase = '<?= $block->url->getMagentOrderDetailUrl(); ?>';
      window.location.href = orderDetailsUrlBase + '/' + orderData.orderId;
    };

    var containerElId = 'ns8-protect-wrapper';

    var requestedPage = '<?= $block->getPageFromRequest(); ?>';
    if (requestedPage === '') {
      requestPage = Protect.ClientPage.DASHBOARD;
    }
    var orderIncrementId = '<?= $block->getOrderIncrementIdFromRequest(); ?>';

    var eventBinding = {};
    eventBinding[Protect.EventName.ORDER_DETAIL_NAME_CLICK] = navigateToMagentoOrderDetails;
    var clientConfig = new Protect.ClientConfig({
      accessToken: '<?= $block->config->getAccessToken(); ?>',
      protectClientUrl: '<?= $block->url->getClientUrl(); ?>',
      eventBinding: eventBinding,
      iFrameConfig: {
        attachToId: containerElId,
        classNames: ['ns8-protect-client-iframe'],
      },
    });
    var protectClient = Protect.createClient(clientConfig);
    protectClient.render(requestedPage, orderIncrementId);
  });
</script>

<div id="ns8-protect-wrapper"></div>
