<?php if ($block->isActivated()) : ?>
    <script type="text/javascript">
      require(['NS8_Protect/js/iframeResizer.min'], function() {

        const container = document.getElementById('ns8-protect-wrapper');
        const protectIframe = document.createElement('iframe');
        const url = '<?= /* @noEscape because URL may contain an ampersand */ $block->getNS8ProtectUrl() ?>';

        protectIframe.src = url
        protectIframe.classList.add('ns8-protect-client-iframe')
        container.appendChild(protectIframe);

        function navigateToMagentoOrderDetails(orderId) {
          const orderDetailsUrlBase = '<?= $block->escapeUrl($block->url->getMagentOrderDetailUrl()); ?>';
          const orderUrl = `${orderDetailsUrlBase}/${orderId}`;
          window.location.href = orderUrl;
        };

        const eventHandlers = {
          'order-detail-name-click': function(data) { navigateToMagentoOrderDetails(data.orderId) },
          'undefined': function() {}
        }

        const [ iframe ] = window.iFrameResize({
          checkOrigin: false,
          heightCalculationMethod: 'lowestElement',
          onMessage: function(payload) {
            eventHandlers[payload.name](payload.data)
          },
          onInit: function(msg) {
            console.log('parent-child connection established: ', msg)
          }
        }, '.ns8-protect-client-iframe')

      });
    </script>
<?php endif ?>

<div id="ns8-protect-wrapper">
    <?php if (!$block->isActivated()) : ?>
        <h3>To Activate Your Integration, Follow These Steps:</h3>

        <div class="activation-steps">
            <ul>
                <li>Log Into Your Magento Admin</li>
                <li>Navigate to "System"</li>
                <li>Navigate to "Integrations"</li>
                <li>Find "NS8 Integration" line item</li>
                <li>Click "Authorize" link</li>
                <li>On the next screen, click the "Authorize" button</li>
            </ul>
        </div>
    <?php endif ?>
</div>
